from estado_municipio_ciudad_asentamiento_zipcode.all_links.all_links import *
from estado_municipio_ciudad_asentamiento_zipcode.all_links.all_links_second import *
import pandas as pd

##########################################################################################
# ALL INFORMATION, ESTADO, MUNICIPIO, CIUDAD, ASENTAMIENTO, ZIP CODE
result = pd.concat([
    # AGUASCALIENTES
    aguas_aguascalientes, aguas_asientos, aguas_calvillo, aguas_cosio,
    aguas_el_llano, aguas_jesus_maria, aguas_pabellon_arteaga, aguas_rincon_romos,
    aguas_sanfrancisco_romos, aguas_sanjose_gracia, aguas_tepezala,
    # BAJA CALIFORNIA
    bajacalifornia_ensenada, bajacalifornia_mexicali, bajacalifornia_playas_rosarito,
    bajacalifornia_sanfelipe, bajacalifornia_sanquintin, bajacalifornia_tecate, bajacalifornia_tijuana,
    # BAJA CALIFORNIA SUR
    bajacalifornia_sur_comundu, bajacalifornia_sur_lapaz, bajacalifornia_sur_loreto,
    bajacalifornia_sur_loscabos, bajacalifornia_sur_mulege,
    # CAMPECHE
    campeche_calakmul, campeche_calkini, campeche_campeche, campeche_candelaria, campeche_carmen,
    campeche_champoton, campeche_dzitbalche, campeche_escarcega, campeche_hecelchakan,
    campeche_hopelchen, campeche_palizada, campeche_seybaplaya, campeche_tenabo,
    # COAHUILA DE ZARAGOZA
    coahuila_abasolo, coahuila_acuna, coahuila_allende, coahuila_arteaga,
    coahuila_candela, coahuila_castanos, coahuila_cuatro_cienegas, coahuila_escobedo,
    coahuila_francisco_madero, coahuila_frontera, coahuila_general_cepeda, coahuila_guerrero,
    coahuila_hidalgo, coahuila_jimenez, coahuila_juarez, coahuila_lamadrid,
    coahuila_matamoros, coahuila_monclova, coahuila_morelos, coahuila_muzquiz,
    coahuila_nadadores, coahuila_nava, coahuila_ocampo, coahuila_parras,
    coahuila_piedras_negras, coahuila_progreso, coahuila_ramos_arizpe,
    coahuila_sabinas, coahuila_sacramento, coahuila_saltillo, coahuila_san_buenaventura,
    coahuila_sanjuan_sabinas, coahuila_san_pedro, coahuila_sierra_mojada, coahuila_torreon,
    coahuila_viesca, coahuila_villa_union, coahuila_zaragoza,
    # COLIMA
    colima_armeria, colima_colima, colima_comala, colima_coquimatlan, colima_cuauhtemoc,
    colima_ixtlahuacan, colima_manzanillo, colima_minatitlan, colima_tecoman, colima_villa_alvarez,
    # CHIAPAS
    Chiapas_acacoyagua, Chiapas_acala, Chiapas_acapetahua, Chiapas_aldama,
    Chiapas_altamirano, Chiapas_amatan, Chiapas_amatenango_frontera, Chiapas_amatenango_valle,
    Chiapas_angel_albino_corzo, Chiapas_arriaga, Chiapas_bejucal_ocampo,
    Chiapas_bella_vista, Chiapas_benemerito_americas, Chiapas_berriozabal, Chiapas_bochil,
    Chiapas_cacahoatan, Chiapas_capitanluis_angelvidal, Chiapas_catazaja, Chiapas_chalchihuitan,
    Chiapas_chamula, Chiapas_chanal, Chiapas_chapultenango, Chiapas_chenalho,
    Chiapas_chiapa_corzo, Chiapas_chiapilla, Chiapas_chicoasen, Chiapas_chicomuselo,
    Chiapas_chilon, Chiapas_cintalapa, Chiapas_coapilla, Chiapas_comitan_dominguez,
    Chiapas_copainala, Chiapas_el_bosque, Chiapas_el_parral, Chiapas_el_porvenir,
    Chiapas_emiliano_zapata, Chiapas_escuintla, Chiapas_francisco_leon,
    Chiapas_frontera_comalapa, Chiapas_frontera_hidalgo, Chiapas_honduras_sierra,
    Chiapas_huehuetan, Chiapas_huitiupan, Chiapas_huixtan, Chiapas_huixtla,
    Chiapas_ixhuatan, Chiapas_ixtacomitan, Chiapas_ixtapa, Chiapas_ixtapangajoya,
    Chiapas_jiquipilas, Chiapas_jitotol, Chiapas_juarez, Chiapas_la_concordia,
    Chiapas_la_grandeza, Chiapas_la_independencia, Chiapas_la_libertad,
    Chiapas_la_trinitaria, Chiapas_larrainzar, Chiapas_las_margaritas, Chiapas_las_rosas,
    Chiapas_mapastepec, Chiapas_maravilla_tenejapa, Chiapas_marques_comillas,
    Chiapas_mazapa_madero, Chiapas_mazatan, Chiapas_metapa, Chiapas_mezcalapa,
    Chiapas_mitontic, Chiapas_montecristo_guerrero, Chiapas_motozintla,
    Chiapas_nicolas_ruiz, Chiapas_ocosingo, Chiapas_ocotepec, Chiapas_ocozocoautla_espinosa,
    Chiapas_ostuacan, Chiapas_osumacinta, Chiapas_oxchuc, Chiapas_palenque,
    Chiapas_pantelho, Chiapas_pantepec, Chiapas_pichucalco, Chiapas_pijijiapan,
    Chiapas_pueblonuevo_solistahuacan, Chiapas_rayon, Chiapas_reforma,
    Chiapas_rinconchamula_sanpedro, Chiapas_sabanilla, Chiapas_salto_agua,
    Chiapas_sanandres_duraznal, Chiapas_sancristobal_casas, Chiapas_san_fernando,
    Chiapas_sanjuan_cancuc, Chiapas_san_lucas, Chiapas_santiago_pinar, Chiapas_siltepec,
    Chiapas_simojovel, Chiapas_sitala, Chiapas_socoltenango, Chiapas_solosuchiapa,
    Chiapas_soyalo, Chiapas_suchiapa, Chiapas_suchiate, Chiapas_sunuapa, Chiapas_tapachula,
    Chiapas_tapalapa, Chiapas_tapilula, Chiapas_tecpatan, Chiapas_tenejapa, Chiapas_teopisca,
    Chiapas_tila, Chiapas_tonala, Chiapas_totolapa, Chiapas_tumbala, Chiapas_tuxtla_chico,
    Chiapas_tuxtla_gutierrez, Chiapas_tuzantan, Chiapas_tzimol, Chiapas_union_juarez,
    Chiapas_venustiano_carranza, Chiapas_villa_comaltitlan, Chiapas_villa_corzo,
    Chiapas_villaflores, Chiapas_yajalon, Chiapas_zinacantan,
    # CHIHUAHUA
    chihuahua_ahumada, chihuahua_aldama, chihuahua_allende, chihuahua_aquiles_serdan,
    chihuahua_ascension, chihuahua_bachiniva, chihuahua_balleza, chihuahua_batopilas_manuelgomez_morin,
    chihuahua_bocoyna, chihuahua_buenaventura, chihuahua_camargo, chihuahua_carichi, chihuahua_casas_grandes,
    chihuahua_chihuahua, chihuahua_chinipas, chihuahua_coronado, chihuahua_coyame_sotol,
    chihuahua_cuauhtemoc, chihuahua_cusihuiriachi, chihuahua_delicias, chihuahua_drbelisario_dominguez,
    chihuahua_eltule, chihuahua_galeana, chihuahua_gomez_farias, chihuahua_gran_morelos, chihuahua_guachochi,
    chihuahua_guadalupe, chihuahua_guadalupe_calvo, chihuahua_guazapares, chihuahua_guerrero,
    chihuahua_hidalgo_parral, chihuahua_huejotitan, chihuahua_ignacio_zaragoza, chihuahua_janos,
    chihuahua_jimenez, chihuahua_juarez, chihuahua_julimes, chihuahua_lacruz, chihuahua_lopez, chihuahua_madera,
    chihuahua_maguarichi, chihuahua_manuel_benavides, chihuahua_matachi, chihuahua_matamoros, chihuahua_meoqui,
    chihuahua_morelos, chihuahua_moris, chihuahua_namiquipa, chihuahua_nonoava, chihuahua_nuevocasas_grandes,
    chihuahua_ocampo, chihuahua_ojinaga, chihuahua_praxedisg_guerrero, chihuahua_riva_palacio, chihuahua_rosales,
    chihuahua_rosario, chihuahua_sanfrancisco_borja, chihuahua_sanfrancisco_conchos, chihuahua_san_francisco_oro,
    chihuahua_santa_barbara, chihuahua_santa_isabel, chihuahua_satevo, chihuahua_saucillo, chihuahua_temosachic,
    chihuahua_urique, chihuahua_uruachi, chihuahua_valle_zaragoza,
    # CIUDAD DE MEXICO
    ciudad_mexico_alvaro_obregon, ciudad_mexico_azcapotzalco, ciudad_mexico_benito_juarez,
    ciudad_mexico_coyoacan, ciudad_mexico_cuajimalpa_morelos, ciudad_mexico_cuauhtemoc,
    ciudad_mexico_gustavo_madero, ciudad_mexico_iztacalco, ciudad_mexico_iztapalapa,
    ciudad_mexico_magdalena_contreras, ciudad_mexico_miguel_hidalgo, ciudad_mexico_milpa_alta,
    ciudad_mexico_tlahuac, ciudad_mexico_tlalpan, ciudad_mexico_venustiano_carranza, ciudad_mexico_xochimilco,
    # DURANGO
    durango_canatlan, durango_canelas, durango_coneto_de_comonfort, durango_cuencame, durango_durango,
    durango_el_oro, durango_general_simon_bolivar, durango_gomez_palacio, durango_guadalupe_victoria,
    durango_guanacevi, durango_hidalgo, durango_inde, durango_lerdo, durango_mapimi, durango_mezquital,
    durango_nazas, durango_nombre_de_dios, durango_nuevo_ideal, durango_ocampo, durango_otaez,
    durango_panuco_de_coronado, durango_penon_blanco, durango_poanas, durango_pueblo_nuevo, durango_rodeo,
    durango_san_bernardo, durango_san_dimas, durango_san_juan_de_guadalupe, durango_san_juan_del_rio,
    durango_san_luis_del_cordero, durango_san_pedro_del_gallo, durango_santa_clara, durango_santiago_papasquiaro,
    durango_suchil, durango_tamazula, durango_tepehuanes, durango_tlahualilo, durango_topia,
    durango_vicente_guerrero,
    # GUANAJUATO
    guanajuato_abasolo, guanajuato_acambaro, guanajuato_apaseo_el_alto, guanajuato_apaseo_el_grande,
    guanajuato_atarjea, guanajuato_celaya, guanajuato_comonfort, guanajuato_coroneo, guanajuato_cortazar,
    guanajuato_cueramaro, guanajuato_doctor_mora, guanajuato_doloreshidalgo_nacional, guanajuato_guanajuato,
    guanajuato_huanimaro, guanajuato_irapuato, guanajuato_jaral_del_progreso, guanajuato_jerecuaro,
    guanajuato_leon, guanajuato_manuel_doblado, guanajuato_moroleon, guanajuato_ocampo, guanajuato_penjamo,
    guanajuato_pueblo_nuevo, guanajuato_purisima_del_rincon, guanajuato_romita, guanajuato_salamanca,
    guanajuato_salvatierra, guanajuato_san_diego_de_la_union, guanajuato_san_felipe,
    guanajuato_san_francisco_del_rincon, guanajuato_san_jose_iturbide, guanajuato_san_luis_de_la_paz,
    guanajuato_san_miguel_de_allende, guanajuato_santa_catarina, guanajuato_santa_cruz_de_juventino_rosas,
    guanajuato_santiago_maravatio, guanajuato_silao_de_la_victoria, guanajuato_tarandacuao, guanajuato_tarimoro,
    guanajuato_tierra_blanca, guanajuato_uriangato, guanajuato_valle_de_santiago, guanajuato_victoria,
    guanajuato_villagran, guanajuato_xichu, guanajuato_yuriria,
    # GUERRERO
    guerrero_acapulco_de_juarez, guerrero_acatepec, guerrero_ahuacuotzingo, guerrero_ajuchitlan_del_progreso,
    guerrero_alcozauca_de_guerrero, guerrero_alpoyeca, guerrero_apaxtla, guerrero_arcelia,
    guerrero_atenango_del_rio, guerrero_atlamajalcingo_del_monte, guerrero_atlixtac, guerrero_atoyac_de_alvarez,
    guerrero_ayutla_de_los_libres, guerrero_azoyu, guerrero_benito_juarez, guerrero_buenavista_de_cuellar,
    guerrero_chilapa_de_alvarez, guerrero_chilpancingo_de_los_bravo, guerrero_coahuayutla_de_jose_maria_izazaga,
    guerrero_cochoapa_el_grande, guerrero_cocula, guerrero_copala, guerrero_copalillo, guerrero_copanatoyac,
    guerrero_coyuca_de_benitez, guerrero_coyuca_de_catalan, guerrero_cuajinicuilapa, guerrero_cualac,
    guerrero_cuautepec, guerrero_cuetzala_del_progreso, guerrero_cutzamala_de_pinzon, guerrero_eduardo_neri,
    guerrero_florencio_villarreal, guerrero_general_canuto_neri, guerrero_general_heliodoro_castillo,
    guerrero_huamuxtitlan, guerrero_huitzuco_de_los_figueroa, guerrero_iguala_de_la_independencia,
    guerrero_igualapa, guerrero_iliatenco, guerrero_ixcateopan_de_cuauhtemoc, guerrero_jose_joaquin_de_herrera,
    guerrero_juan_escudero, guerrero_juchitan, guerrero_la_union_de_isidoro_montes_de_oca,
    guerrero_leonardo_bravo, guerrero_malinaltepec, guerrero_marquelia, guerrero_martir_de_cuilapan,
    guerrero_metlatonoc, guerrero_mochitlan, guerrero_olinala, guerrero_ometepec, guerrero_pedro_ascencio_alquisiras,
    guerrero_petatlan, guerrero_pilcaya, guerrero_pungarabato, guerrero_quechultenango,
    guerrero_san_luis_acatlan, guerrero_san_marcos, guerrero_san_miguel_totolapan,
    guerrero_taxco_de_alarcon, guerrero_tecoanapa, guerrero_tecpan_de_galeana,
    guerrero_teloloapan, guerrero_tepecoacuilco_de_trujano, guerrero_tetipac,
    guerrero_tixtla_de_guerrero, guerrero_tlacoachistlahuaca, guerrero_tlacoapa,
    guerrero_tlalchapa, guerrero_tlalixtaquilla_de_maldonado, guerrero_tlapa_de_comonfort,
    guerrero_tlapehuala, guerrero_xalpatlahuac, guerrero_xochihuehuetlan, guerrero_xochistlahuaca,
    guerrero_zapotitlan_tablas, guerrero_zihuatanejo_de_azueta, guerrero_zirandaro, guerrero_zitlala,
    # HIDALGO
    hidalgo_acatlan, hidalgo_acaxochitlan, hidalgo_actopan, hidalgo_agua_blanca_de_iturbide, hidalgo_ajacuba,
    hidalgo_alfajayucan, hidalgo_almoloya, hidalgo_apan, hidalgo_atitalaquia, hidalgo_atlapexco,
    hidalgo_atotonilco_de_tula, hidalgo_atotonilco_el_grande, hidalgo_calnali, hidalgo_cardonal,
    hidalgo_chapantongo, hidalgo_chapulhuacan, hidalgo_chilcuautla, hidalgo_cuautepec_de_hinojosa,
    hidalgo_el_arenal, hidalgo_eloxochitlan, hidalgo_emiliano_zapata, hidalgo_epazoyucan,
    hidalgo_francisco__madero, hidalgo_huasca_de_ocampo, hidalgo_huautla, hidalgo_huazalingo,
    hidalgo_huehuetla, hidalgo_huejutla_de_reyes, hidalgo_huichapan, hidalgo_ixmiquilpan,
    hidalgo_jacala_de_ledezma, hidalgo_jaltocan, hidalgo_juarez_hidalgo, hidalgo_la_mision,
    hidalgo_lolotla, hidalgo_metepec, hidalgo_metztitlan, hidalgo_mineral_reforma,
    hidalgo_mineral_chico, hidalgo_mineral_monte, hidalgo_mixquiahuala_de_juarez,
    hidalgo_molango_escamilla, hidalgo_nicolas_flores, hidalgo_nopala_villagran,
    hidalgo_omitlan_juarez, hidalgo_pachuca_soto, hidalgo_pacula, hidalgo_pisaflores,
    hidalgo_progreso_obregon, hidalgo_san_agustin_metzquititlan, hidalgo_san_agustin_tlaxiaca,
    hidalgo_san_bartolo_tutotepec, hidalgo_san_felipe_orizatlan, hidalgo_san_salvador, hidalgo_santiago_de_anaya,
    hidalgo_santiagotulantepec_lugo_guerrero, hidalgo_singuilucan, hidalgo_tasquillo, hidalgo_tecozautla,
    hidalgo_tenango_de_doria, hidalgo_tepeapulco, hidalgo_tepehuacan_de_guerrero, hidalgo_tepeji_del_rio_de_ocampo,
    hidalgo_tepetitlan, hidalgo_tetepango, hidalgo_tezontepec_de_aldama, hidalgo_tianguistengo, hidalgo_tizayuca,
    hidalgo_tlahuelilpan, hidalgo_tlahuiltepa, hidalgo_tlanalapa, hidalgo_tlanchinol, hidalgo_tlaxcoapan,
    hidalgo_tolcayuca, hidalgo_tula_de_allende, hidalgo_tulancingo_de_bravo, hidalgo_villa_de_tezontepec,
    hidalgo_xochiatipan, hidalgo_xochicoatlan, hidalgo_yahualica, hidalgo_zacualtipan_de_angeles,
    hidalgo_zapotlan_de_juarez, hidalgo_zempoala, hidalgo_zimapan,
    # JALISCO
    jalisco_acatic, jalisco_acatlan_de_juarez, jalisco_ahualulco_de_mercado, jalisco_amacueca, jalisco_amatitan,
    jalisco_ameca, jalisco_arandas, jalisco_atemajac_de_brizuela, jalisco_atengo, jalisco_atenguillo,
    jalisco_atotonilco_el_alto, jalisco_atoyac, jalisco_autlan_de_navarro, jalisco_ayotlan, jalisco_ayutla,
    jalisco_bolanos, jalisco_cabo_corrientes, jalisco_canadas_de_obregon, jalisco_casimiro_castillo,
    jalisco_chapala, jalisco_chimaltitan, jalisco_chiquilistlan, jalisco_cihuatlan, jalisco_cocula,
    jalisco_colotlan, jalisco_concepcion_de_buenos_aires, jalisco_cuautitlan_de_garcia_barragan,
    jalisco_cuautla, jalisco_cuquio, jalisco_degollado, jalisco_ejutla, jalisco_el_arenal, jalisco_el_grullo,
    jalisco_el_limon, jalisco_el_salto, jalisco_encarnacion_de_diaz, jalisco_etzatlan, jalisco_gomez_farias,
    jalisco_guachinango, jalisco_guadalajara, jalisco_hostotipaquillo, jalisco_huejucar, jalisco_huejuquilla_el_alto,
    jalisco_ixtlahuacan_de_los_membrillos, jalisco_ixtlahuacan_del_rio, jalisco_jalostotitlan, jalisco_jamay,
    jalisco_jesus_maria, jalisco_jilotlan_de_los_dolores, jalisco_jocotepec, jalisco_juanacatlan, jalisco_juchitlan,
    jalisco_la_barca, jalisco_la_huerta, jalisco_la_manzanilla_de_la_paz, jalisco_lagos_de_moreno, jalisco_magdalena,
    jalisco_mascota, jalisco_mazamitla, jalisco_mexticacan, jalisco_mezquitic, jalisco_mixtlan, jalisco_ocotlan,
    jalisco_ojuelos_de_jalisco, jalisco_pihuamo, jalisco_poncitlan, jalisco_puerto_vallarta, jalisco_quitupan,
    jalisco_san_cristobal_de_la_barranca, jalisco_san_diego_de_alejandria, jalisco_san_gabriel,
    jalisco_san_ignacio_cerro_gordo, jalisco_san_juan_de_los_lagos, jalisco_san_juanito_de_escobedo,
    jalisco_san_julian, jalisco_san_marcos, jalisco_san_martin_de_bolanos, jalisco_san_martin_hidalgo,
    jalisco_san_miguel_el_alto, jalisco_san_pedro_tlaquepaque, jalisco_san_sebastian_del_oeste,
    jalisco_santa_maria_de_los_angeles, jalisco_santa_maria_del_oro, jalisco_sayula, jalisco_tala,
    jalisco_talpa_de_allende, jalisco_tamazula_de_gordiano, jalisco_tapalpa, jalisco_tecalitlan,
    jalisco_techaluta_de_montenegro, jalisco_tecolotlan, jalisco_tenamaxtlan, jalisco_teocaltiche,
    jalisco_teocuitatlan_de_corona, jalisco_tepatitlan_de_morelos, jalisco_tequila, jalisco_teuchitlan,
    jalisco_tizapan_el_alto, jalisco_tlajomulco_de_zuniga, jalisco_toliman, jalisco_tomatlan, jalisco_tonala,
    jalisco_tonaya, jalisco_tonila, jalisco_totatiche, jalisco_tototlan, jalisco_tuxcacuesco, jalisco_tuxcueca,
    jalisco_tuxpan, jalisco_union_de_san_antonio, jalisco_union_de_tula, jalisco_valle_de_guadalupe,
    jalisco_valle_de_juarez, jalisco_villa_corona, jalisco_villa_guerrero, jalisco_villa_hidalgo,
    jalisco_villa_purificacion, jalisco_yahualica_de_gonzalez_gallo, jalisco_zacoalco_de_torres, jalisco_zapopan,
    jalisco_zapotiltic, jalisco_zapotitlan_de_vadillo, jalisco_zapotlan_del_rey, jalisco_zapotlan_el_grande,
    jalisco_zapotlanejo,
    # ESTADO DE MEXICO
    estado_mexico_acambay_de_ruiz_castaneda, estado_mexico_acolman, estado_mexico_aculco,
    estado_mexico_almoloya_de_alquisiras, estado_mexico_almoloya_de_juarez, estado_mexico_almoloya_del_rio,
    estado_mexico_amanalco, estado_mexico_amatepec, estado_mexico_amecameca, estado_mexico_apaxco,
    estado_mexico_atenco, estado_mexico_atizapan, estado_mexico_atizapan_de_zaragoza, estado_mexico_atlacomulco,
    estado_mexico_atlautla, estado_mexico_axapusco, estado_mexico_ayapango, estado_mexico_calimaya,
    estado_mexico_capulhuac, estado_mexico_chalco, estado_mexico_chapa_de_mota, estado_mexico_chapultepec,
    estado_mexico_chiautla, estado_mexico_chicoloapan, estado_mexico_chiconcuac, estado_mexico_chimalhuacan,
    estado_mexico_coacalco_de_berriozabal, estado_mexico_coatepec_harinas, estado_mexico_cocotitlan,
    estado_mexico_coyotepec, estado_mexico_cuautitlan, estado_mexico_cuautitlan_izcalli, estado_mexico_donato_guerra,
    estado_mexico_ecatepec_de_morelos, estado_mexico_ecatzingo, estado_mexico_el_oro, estado_mexico_huehuetoca,
    estado_mexico_hueypoxtla, estado_mexico_huixquilucan, estado_mexico_isidro_fabela, estado_mexico_ixtapaluca,
    estado_mexico_ixtapan_de_la_sal, estado_mexico_ixtapan_del_oro, estado_mexico_ixtlahuaca, estado_mexico_jaltenco,
    estado_mexico_jilotepec, estado_mexico_jilotzingo, estado_mexico_jiquipilco, estado_mexico_jocotitlan,
    estado_mexico_joquicingo, estado_mexico_juchitepec, estado_mexico_la_paz, estado_mexico_lerma, estado_mexico_luvianos,
    estado_mexico_malinalco, estado_mexico_melchor_ocampo, estado_mexico_metepec, estado_mexico_mexicaltzingo,
    estado_mexico_morelos, estado_mexico_naucalpan_de_juarez, estado_mexico_nextlalpan, estado_mexico_nezahualcoyotl,
    estado_mexico_nicolas_romero, estado_mexico_nopaltepec, estado_mexico_ocoyoacac, estado_mexico_ocuilan,
    estado_mexico_otumba, estado_mexico_otzoloapan, estado_mexico_otzolotepec, estado_mexico_ozumba,
    estado_mexico_papalotla, estado_mexico_polotitlan, estado_mexico_rayon, estado_mexico_san_antonio_la_isla,
    estado_mexico_san_felipe_del_progreso, estado_mexico_san_jose_del_rincon, estado_mexico_san_martin_de_las_piramides,
    estado_mexico_san_mateo_atenco, estado_mexico_san_simon_de_guerrero, estado_mexico_santo_tomas,
    estado_mexico_soyaniquilpan_de_juarez, estado_mexico_sultepec, estado_mexico_tecamac, estado_mexico_tejupilco,
    estado_mexico_temamatla, estado_mexico_temascalapa, estado_mexico_temascalcingo, estado_mexico_temascaltepec,
    estado_mexico_temoaya, estado_mexico_tenancingo, estado_mexico_tenango_del_aire, estado_mexico_tenango_del_valle,
    estado_mexico_teoloyucan, estado_mexico_teotihuacan, estado_mexico_tepetlaoxtoc, estado_mexico_tepetlixpa,
    estado_mexico_tepotzotlan, estado_mexico_tequixquiac, estado_mexico_texcaltitlan, estado_mexico_texcalyacac,
    estado_mexico_texcoco, estado_mexico_tezoyuca, estado_mexico_tianguistenco, estado_mexico_timilpan, estado_mexico_tlalmanalco,
    estado_mexico_tlalnepantla_de_baz, estado_mexico_tlatlaya, estado_mexico_toluca, estado_mexico_tonanitla, estado_mexico_tonatico,
    estado_mexico_tultepec, estado_mexico_tultitlan, estado_mexico_valle_de_bravo, estado_mexico_valle_de_chalco_solidaridad,
    estado_mexico_villa_de_allende, estado_mexico_villa_del_carbon, estado_mexico_villa_guerrero, estado_mexico_villa_victoria,
    estado_mexico_xalatlaco, estado_mexico_xonacatlan, estado_mexico_zacazonapan, estado_mexico_zacualpan, estado_mexico_zinacantepec,
    estado_mexico_zumpahuacan, estado_mexico_zumpango,
    # MICHOACAN DE OCAMPO
    michoacan_ocampo_acuitzio, michoacan_ocampo_aguililla, michoacan_ocampo_alvaro_obregon, michoacan_ocampo_angamacutiro,
    michoacan_ocampo_angangueo, michoacan_ocampo_apatzingan, michoacan_ocampo_aporo, michoacan_ocampo_aquila,
    michoacan_ocampo_ario, michoacan_ocampo_arteaga, michoacan_ocampo_brisenas, michoacan_ocampo_buenavista,
    michoacan_ocampo_caracuaro, michoacan_ocampo_charapan, michoacan_ocampo_charo, michoacan_ocampo_chavinda,
    michoacan_ocampo_cheran, michoacan_ocampo_chilchota, michoacan_ocampo_chinicuila, michoacan_ocampo_chucandiro,
    michoacan_ocampo_churintzio, michoacan_ocampo_churumuco, michoacan_ocampo_coahuayana,
    michoacan_ocampo_coalcoman_de_vazquez_pallares, michoacan_ocampo_coeneo, michoacan_ocampo_cojumatlan_de_regules,
    michoacan_ocampo_contepec, michoacan_ocampo_copandaro, michoacan_ocampo_cotija,
    michoacan_ocampo_cuitzeo, michoacan_ocampo_ecuandureo, michoacan_ocampo_epitacio_huerta, michoacan_ocampo_erongaricuaro,
    michoacan_ocampo_gabriel_zamora, michoacan_ocampo_hidalgo, michoacan_ocampo_huandacareo, michoacan_ocampo_huaniqueo,
    michoacan_ocampo_huetamo, michoacan_ocampo_huiramba, michoacan_ocampo_indaparapeo, michoacan_ocampo_irimbo,
    michoacan_ocampo_ixtlan, michoacan_ocampo_jacona, michoacan_ocampo_jimenez, michoacan_ocampo_jiquilpan,
    michoacan_ocampo_jose_sixto_verduzco, michoacan_ocampo_juarez, michoacan_ocampo_jungapeo, michoacan_ocampo_la_huacana,
    michoacan_ocampo_la_piedad, michoacan_ocampo_lagunillas, michoacan_ocampo_lazaro_cardenas, michoacan_ocampo_los_reyes,
    michoacan_ocampo_madero, michoacan_ocampo_maravatio, michoacan_ocampo_marcos_castellanos, michoacan_ocampo_morelia,
    michoacan_ocampo_morelos, michoacan_ocampo_mugica, michoacan_ocampo_nahuatzen, michoacan_ocampo_nocupetaro,
    michoacan_ocampo_nuevo_parangaricutiro, michoacan_ocampo_nuevo_urecho, michoacan_ocampo_numaran, michoacan_ocampo_ocampo,
    michoacan_ocampo_pajacuaran, michoacan_ocampo_panindicuaro, michoacan_ocampo_paracho, michoacan_ocampo_paracuaro,
    michoacan_ocampo_patzcuaro, michoacan_ocampo_penjamillo, michoacan_ocampo_periban, michoacan_ocampo_purepero,
    michoacan_ocampo_puruandiro, michoacan_ocampo_querendaro, michoacan_ocampo_quiroga, michoacan_ocampo_sahuayo,
    michoacan_ocampo_salvador_escalante, michoacan_ocampo_san_lucas, michoacan_ocampo_santa_ana_maya, michoacan_ocampo_senguio,
    michoacan_ocampo_susupuato, michoacan_ocampo_tacambaro, michoacan_ocampo_tancitaro, michoacan_ocampo_tangamandapio,
    michoacan_ocampo_tangancicuaro, michoacan_ocampo_tanhuato, michoacan_ocampo_taretan, michoacan_ocampo_tarimbaro,
    michoacan_ocampo_tepalcatepec, michoacan_ocampo_tingambato, michoacan_ocampo_tinguindin,
    michoacan_ocampo_tiquicheo_de_nicolas_romero, michoacan_ocampo_tlalpujahua, michoacan_ocampo_tlazazalca,
    michoacan_ocampo_tocumbo, michoacan_ocampo_tumbiscatio, michoacan_ocampo_turicato, michoacan_ocampo_tuxpan,
    michoacan_ocampo_tuzantla, michoacan_ocampo_tzintzuntzan, michoacan_ocampo_tzitzio, michoacan_ocampo_uruapan,
    michoacan_ocampo_venustiano_carranza, michoacan_ocampo_villamar, michoacan_ocampo_vista_hermosa, michoacan_ocampo_yurecuaro,
    michoacan_ocampo_zacapu, michoacan_ocampo_zamora, michoacan_ocampo_zinaparo, michoacan_ocampo_zinapecuaro,
    michoacan_ocampo_ziracuaretiro, michoacan_ocampo_zitacuaro,
    # MORELOS
    morelos_amacuzac, morelos_atlatlahucan, morelos_axochiapan, morelos_ayala, morelos_coatetelco,
    morelos_coatlan_del_rio, morelos_cuautla, morelos_cuernavaca, morelos_emiliano_zapata,
    morelos_hueyapan, morelos_huitzilac, morelos_jantetelco, morelos_jiutepec, morelos_jojutla,
    morelos_jonacatepec_de_leandro_valle, morelos_mazatepec, morelos_miacatlan, morelos_ocuituco,
    morelos_puente_de_ixtla, morelos_temixco, morelos_temoac, morelos_tepalcingo, morelos_tepoztlan,
    morelos_tetecala, morelos_tetela_del_volcan, morelos_tlalnepantla, morelos_tlaltizapan_de_zapata,
    morelos_tlaquiltenango, morelos_tlayacapan, morelos_totolapan, morelos_xochitepec, morelos_xoxocotla,
    morelos_yautepec, morelos_yecapixtla, morelos_zacatepec, morelos_zacualpan_de_amilpas,
    # NAYARIT
    nayarit_acaponeta, nayarit_ahuacatlan, nayarit_amatlan_de_canas, nayarit_bahia_de_banderas, nayarit_compostela,
    nayarit_del_nayar, nayarit_huajicori, nayarit_ixtlan_del_rio, nayarit_jala, nayarit_la_yesca, nayarit_rosamorada,
    nayarit_ruiz, nayarit_san_blas, nayarit_san_pedro_lagunillas, nayarit_santa_maria_del_oro, nayarit_santiago_ixcuintla,
    nayarit_tecuala, nayarit_tepic, nayarit_tuxpan, nayarit_xalisco,
    # NUEVO LEON
    nuevo_leon_abasolo, nuevo_leon_agualeguas, nuevo_leon_allende, nuevo_leon_anahuac, nuevo_leon_apodaca,
    nuevo_leon_aramberri, nuevo_leon_bustamante, nuevo_leon_cadereyta_jimenez, nuevo_leon_cerralvo,
    nuevo_leon_china, nuevo_leon_cienega_de_flores, nuevo_leon_doctor_arroyo, nuevo_leon_doctor_coss,
    nuevo_leon_doctor_gonzalez, nuevo_leon_el_carmen, nuevo_leon_galeana, nuevo_leon_garcia, nuevo_leon_general_bravo,
    nuevo_leon_general_escobedo, nuevo_leon_general_teran, nuevo_leon_general_trevino, nuevo_leon_general_zaragoza,
    nuevo_leon_general_zuazua, nuevo_leon_guadalupe, nuevo_leon_hidalgo, nuevo_leon_higueras, nuevo_leon_hualahuises,
    nuevo_leon_iturbide, nuevo_leon_juarez, nuevo_leon_lampazos_de_naranjo, nuevo_leon_linares, nuevo_leon_los_aldamas,
    nuevo_leon_los_herreras, nuevo_leon_los_ramones, nuevo_leon_marin, nuevo_leon_melchor_ocampo, nuevo_leon_mier_y_noriega,
    nuevo_leon_mina, nuevo_leon_montemorelos, nuevo_leon_monterrey, nuevo_leon_paras, nuevo_leon_pesqueria, nuevo_leon_rayones,
    nuevo_leon_sabinas_hidalgo, nuevo_leon_salinas_victoria, nuevo_leon_san_nicolas_de_los_garza,
    nuevo_leon_san_pedro_garza_garcia, nuevo_leon_santa_catarina, nuevo_leon_santiago, nuevo_leon_vallecillo, nuevo_leon_villaldama,
    # OAXACA
    oaxaca_abejones, oaxaca_acatlan_de_perez_figueroa, oaxaca_animas_trujano, oaxaca_asuncion_cacalotepec,
    oaxaca_asuncion_cuyotepeji, oaxaca_asuncion_ixtaltepec, oaxaca_asuncion_nochixtlan, oaxaca_asuncion_ocotlan,
    oaxaca_asuncion_tlacolulita, oaxaca_ayoquezco_de_aldama, oaxaca_ayotzintepec, oaxaca_calihuala,
    oaxaca_candelaria_loxicha, oaxaca_capulalpam_de_mendez, oaxaca_chahuites, oaxaca_chalcatongo_de_hidalgo,
    oaxaca_chiquihuitlan_de_benito_juarez, oaxaca_cienega_de_zimatlan, oaxaca_ciudad_ixtepec, oaxaca_coatecas_altas,
    oaxaca_coicoyan_de_las_flores, oaxaca_concepcion_buenavista, oaxaca_concepcion_papalo, oaxaca_constancia_del_rosario,
    oaxaca_cosolapa, oaxaca_cosoltepec, oaxaca_cuilapam_de_guerrero, oaxaca_cuyamecalco_villa_de_zaragoza,
    oaxaca_el_barrio_de_la_soledad, oaxaca_el_espinal, oaxaca_eloxochitlan_de_flores_magon, oaxaca_fresnillo_de_trujano,
    oaxaca_guadalupe_de_ramirez, oaxaca_guadalupe_etla, oaxaca_guelatao_de_juarez, oaxaca_guevea_de_humboldt,
    oaxaca_heroica_ciudad_de_ejutla_de_crespo, oaxaca_heroica_ciudad_de_huajuapan_de_leon, oaxaca_heroica_ciudad_de_tlaxiaco,
    oaxaca_huautepec, oaxaca_huautla_de_jimenez, oaxaca_ixpantepec_nieves, oaxaca_ixtlan_de_juarez, oaxaca_juchitan_de_zaragoza,
    oaxaca_la_compania, oaxaca_la_pe, oaxaca_la_reforma, oaxaca_la_trinidad_vista_hermosa, oaxaca_loma_bonita,
    oaxaca_magdalena_apasco, oaxaca_magdalena_jaltepec, oaxaca_magdalena_mixtepec, oaxaca_magdalena_ocotlan,
    oaxaca_magdalena_penasco, oaxaca_magdalena_teitipac, oaxaca_magdalena_tequisistlan, oaxaca_magdalena_tlacotepec,
    oaxaca_magdalena_yodocono_de_porfirio_diaz, oaxaca_magdalena_zahuatlan, oaxaca_mariscala_de_juarez, oaxaca_martires_de_tacubaya,
    oaxaca_matias_romero_avendano, oaxaca_mazatlan_villa_de_flores, oaxaca_mesones_hidalgo, oaxaca_miahuatlan_de_porfirio_diaz,
    oaxaca_mixistlan_de_la_reforma, oaxaca_monjas, oaxaca_natividad, oaxaca_nazareno_etla, oaxaca_nejapa_de_madero,
    oaxaca_nuevo_zoquiapam, oaxaca_oaxaca_de_juarez, oaxaca_ocotlan_de_morelos, oaxaca_pinotepa_de_don_luis, oaxaca_pluma_hidalgo,
    oaxaca_putla_villa_de_guerrero, oaxaca_reforma_de_pineda, oaxaca_reyes_etla, oaxaca_rojas_de_cuauhtemoc, oaxaca_salina_cruz,
    oaxaca_san_agustin_amatengo, oaxaca_san_agustin_atenango, oaxaca_san_agustin_chayuco, oaxaca_san_agustin_de_las_juntas,
    oaxaca_san_agustin_etla, oaxaca_san_agustin_loxicha, oaxaca_san_agustin_tlacotepec, oaxaca_san_agustin_yatareni,
    oaxaca_san_andres_cabecera_nueva, oaxaca_san_andres_dinicuiti, oaxaca_san_andres_huaxpaltepec, oaxaca_san_andres_huayapam,
    oaxaca_san_andres_ixtlahuaca, oaxaca_san_andres_lagunas, oaxaca_san_andres_nuxino, oaxaca_san_andres_paxtlan, oaxaca_san_andres_sinaxtla,
    oaxaca_san_andres_solaga, oaxaca_san_andres_teotilalpam, oaxaca_san_andres_tepetlapa, oaxaca_san_andres_yaa, oaxaca_san_andres_zabache,
    oaxaca_san_andres_zautla, oaxaca_san_antonino_castillo_velasco, oaxaca_san_antonino_el_alto, oaxaca_san_antonino_monte_verde,
    oaxaca_san_antonio_acutla, oaxaca_san_antonio_de_la_cal, oaxaca_san_antonio_huitepec, oaxaca_san_antonio_nanahuatipam,
    oaxaca_san_antonio_sinicahua, oaxaca_san_antonio_tepetlapa, oaxaca_san_baltazar_chichicapam, oaxaca_san_baltazar_loxicha,
    oaxaca_san_baltazar_yatzachi_el_bajo, oaxaca_san_bartolo_coyotepec, oaxaca_san_bartolo_soyaltepec, oaxaca_san_bartolo_yautepec,
    oaxaca_san_bartolome_ayautla, oaxaca_san_bartolome_loxicha, oaxaca_san_bartolome_quialana, oaxaca_san_bartolome_yucuane,
    oaxaca_san_bartolome_zoogocho, oaxaca_san_bernardo_mixtepec, oaxaca_san_blas_atempa, oaxaca_san_carlos_yautepec,
    oaxaca_san_cristobal_amatlan, oaxaca_san_cristobal_amoltepec, oaxaca_san_cristobal_lachirioag, oaxaca_san_cristobal_suchixtlahuaca,
    oaxaca_san_dionisio_del_mar, oaxaca_san_dionisio_ocotepec, oaxaca_san_dionisio_ocotlan, oaxaca_san_esteban_atatlahuca,
    oaxaca_san_felipe_jalapa_de_diaz, oaxaca_san_felipe_tejalapam, oaxaca_san_felipe_usila, oaxaca_san_francisco_cahuacua,
    oaxaca_san_francisco_cajonos, oaxaca_san_francisco_chapulapa, oaxaca_san_francisco_chindua, oaxaca_san_francisco_del_mar,
    oaxaca_san_francisco_huehuetlan, oaxaca_san_francisco_ixhuatan, oaxaca_san_francisco_jaltepetongo, oaxaca_san_francisco_lachigolo,
    oaxaca_san_francisco_logueche, oaxaca_san_francisco_nuxano, oaxaca_san_francisco_ozolotepec, oaxaca_san_francisco_sola,
    oaxaca_san_francisco_telixtlahuaca, oaxaca_san_francisco_teopan, oaxaca_san_francisco_tlapancingo, oaxaca_san_gabriel_mixtepec,
    oaxaca_san_ildefonso_amatlan, oaxaca_san_ildefonso_sola, oaxaca_san_ildefonso_villa_alta, oaxaca_san_jacinto_amilpas,
    oaxaca_san_jacinto_tlacotepec, oaxaca_san_jeronimo_coatlan, oaxaca_san_jeronimo_silacayoapilla, oaxaca_san_jeronimo_sosola,
    oaxaca_san_jeronimo_taviche, oaxaca_san_jeronimo_tecoatl, oaxaca_san_jeronimo_tlacochahuaya, oaxaca_san_jorge_nuchita,
    oaxaca_san_jose_ayuquila, oaxaca_san_jose_chiltepec, oaxaca_san_jose_del_penasco, oaxaca_san_jose_del_progreso,
    oaxaca_san_jose_estancia_grande, oaxaca_san_jose_independencia, oaxaca_san_jose_lachiguiri, oaxaca_san_jose_tenango,
    oaxaca_san_juan_achiutla, oaxaca_san_juan_atepec, oaxaca_san_juan_bautista_atatlahuca, oaxaca_san_juan_bautista_coixtlahuaca,
    oaxaca_san_juan_bautista_cuicatlan, oaxaca_san_juan_bautista_guelache, oaxaca_san_juan_bautista_jayacatlan,
    oaxaca_san_juan_bautista_lo_de_soto, oaxaca_san_juan_bautista_suchitepec, oaxaca_san_juan_bautista_tlachichilco,
    oaxaca_san_juan_bautista_tlacoatzintepec, oaxaca_san_juan_bautista_tuxtepec, oaxaca_san_juan_bautista_valle_nacional,
    oaxaca_san_juan_cacahuatepec, oaxaca_san_juan_chicomezuchil, oaxaca_san_juan_chilateca, oaxaca_san_juan_cieneguilla,
    oaxaca_san_juan_coatzospam, oaxaca_san_juan_colorado, oaxaca_san_juan_comaltepec, oaxaca_san_juan_cotzocon,
    oaxaca_san_juan_de_los_cues, oaxaca_san_juan_del_estado, oaxaca_san_juan_del_rio, oaxaca_san_juan_diuxi,
    oaxaca_san_juan_evangelista_analco, oaxaca_san_juan_guelavia, oaxaca_san_juan_guichicovi, oaxaca_san_juan_ihualtepec,
    oaxaca_san_juan_juquila_mixes, oaxaca_san_juan_juquila_vijanos, oaxaca_san_juan_lachao, oaxaca_san_juan_lachigalla,
    oaxaca_san_juan_lajarcia, oaxaca_san_juan_lalana, oaxaca_san_juan_mazatlan, oaxaca_san_juan_mixtepec_dto_08,
    oaxaca_san_juan_mixtepec_dto_26_, oaxaca_san_juan_numi, oaxaca_san_juan_ozolotepec, oaxaca_san_juan_petlapa,
    oaxaca_san_juan_quiahije, oaxaca_san_juan_quiotepec, oaxaca_san_juan_sayultepec, oaxaca_san_juan_tabaa, oaxaca_san_juan_tamazola,
    oaxaca_san_juan_teita, oaxaca_san_juan_teitipac, oaxaca_san_juan_tepeuxila, oaxaca_san_juan_teposcolula, oaxaca_san_juan_yaee,
    oaxaca_san_juan_yatzona, oaxaca_san_juan_yucuita, oaxaca_san_lorenzo, oaxaca_san_lorenzo_albarradas, oaxaca_san_lorenzo_cacaotepec,
    oaxaca_san_lorenzo_cuaunecuiltitla, oaxaca_san_lorenzo_texmelucan, oaxaca_san_lorenzo_victoria, oaxaca_san_lucas_camotlan,
    oaxaca_san_lucas_ojitlan, oaxaca_san_lucas_quiavini, oaxaca_san_lucas_zoquiapam, oaxaca_san_luis_amatlan, oaxaca_san_marcial_ozolotepec,
    oaxaca_san_marcos_arteaga, oaxaca_san_martin_de_los_cansecos, oaxaca_san_martin_huamelulpam, oaxaca_san_martin_itunyoso,
    oaxaca_san_martin_lachila, oaxaca_san_martin_peras, oaxaca_san_martin_tilcajete, oaxaca_san_martin_toxpalan, oaxaca_san_martin_zacatepec,
    oaxaca_san_mateo_cajonos, oaxaca_san_mateo_del_mar, oaxaca_san_mateo_etlatongo, oaxaca_san_mateo_nejapam, oaxaca_san_mateo_penasco,
    oaxaca_san_mateo_pinas, oaxaca_san_mateo_rio_hondo, oaxaca_san_mateo_sindihui, oaxaca_san_mateo_tlapiltepec,
    oaxaca_san_mateo_yoloxochitlan, oaxaca_san_mateo_yucutindoo, oaxaca_san_melchor_betaza, oaxaca_san_miguel_achiutla,
    oaxaca_san_miguel_ahuehuetitlan, oaxaca_san_miguel_aloapam, oaxaca_san_miguel_amatitlan, oaxaca_san_miguel_amatlan,
    oaxaca_san_miguel_chicahua, oaxaca_san_miguel_chimalapa, oaxaca_san_miguel_coatlan, oaxaca_san_miguel_del_puerto, oaxaca_san_miguel_del_rio,
    oaxaca_san_miguel_ejutla, oaxaca_san_miguel_el_grande, oaxaca_san_miguel_huautla, oaxaca_san_miguel_mixtepec,
    oaxaca_san_miguel_panixtlahuaca, oaxaca_san_miguel_peras, oaxaca_san_miguel_piedras, oaxaca_san_miguel_quetzaltepec,
    oaxaca_san_miguel_santa_flor, oaxaca_san_miguel_soyaltepec, oaxaca_san_miguel_suchixtepec, oaxaca_san_miguel_tecomatlan,
    oaxaca_san_miguel_tenango, oaxaca_san_miguel_tequixtepec, oaxaca_san_miguel_tilquiapam, oaxaca_san_miguel_tlacamama,
    oaxaca_san_miguel_tlacotepec, oaxaca_san_miguel_tulancingo, oaxaca_san_miguel_yotao, oaxaca_san_nicolas, oaxaca_san_nicolas_hidalgo,
    oaxaca_san_pablo_coatlan, oaxaca_san_pablo_cuatro_venados, oaxaca_san_pablo_etla, oaxaca_san_pablo_huitzo, oaxaca_san_pablo_huixtepec,
    oaxaca_san_pablo_macuiltianguis, oaxaca_san_pablo_tijaltepec, oaxaca_san_pablo_villa_de_mitla, oaxaca_san_pablo_yaganiza,
    oaxaca_san_pedro_amuzgos, oaxaca_san_pedro_apostol, oaxaca_san_pedro_atoyac, oaxaca_san_pedro_cajonos, oaxaca_san_pedro_comitancillo,
    oaxaca_san_pedro_coxcaltepec_cantaros, oaxaca_san_pedro_el_alto, oaxaca_san_pedro_huamelula, oaxaca_san_pedro_huilotepec,
    oaxaca_san_pedro_ixcatlan, oaxaca_san_pedro_ixtlahuaca, oaxaca_san_pedro_jaltepetongo, oaxaca_san_pedro_jicayan, oaxaca_san_pedro_jocotipac,
    oaxaca_san_pedro_juchatengo, oaxaca_san_pedro_martir, oaxaca_san_pedro_martir_quiechapa, oaxaca_san_pedro_martir_yucuxaco,
    oaxaca_san_pedro_mixtepec_dto_22, oaxaca_san_pedro_mixtepec_dto_26, oaxaca_san_pedro_molinos, oaxaca_san_pedro_nopala,
    oaxaca_san_pedro_ocopetatillo, oaxaca_san_pedro_ocotepec, oaxaca_san_pedro_pochutla, oaxaca_san_pedro_quiatoni, oaxaca_san_pedro_sochiapam,
    oaxaca_san_pedro_tapanatepec, oaxaca_san_pedro_taviche, oaxaca_san_pedro_teozacoalco, oaxaca_san_pedro_teutila, oaxaca_san_pedro_tidaa,
    oaxaca_san_pedro_topiltepec, oaxaca_san_pedro_totolapam, oaxaca_san_pedro_y_san_pablo_ayutla, oaxaca_san_pedro_y_san_pablo_teposcolula,
    oaxaca_san_pedro_y_san_pablo_tequixtepec, oaxaca_san_pedro_yaneri, oaxaca_san_pedro_yolox, oaxaca_san_pedro_yucunama,
    oaxaca_san_raymundo_jalpan, oaxaca_san_sebastian_abasolo, oaxaca_san_sebastian_coatlan, oaxaca_san_sebastian_ixcapa,
    oaxaca_san_sebastian_nicananduta, oaxaca_san_sebastian_rio_hondo, oaxaca_san_sebastian_tecomaxtlahuaca, oaxaca_san_sebastian_teitipac,
    oaxaca_san_sebastian_tutla, oaxaca_san_simon_almolongas, oaxaca_san_simon_zahuatlan, oaxaca_san_vicente_coatlan, oaxaca_san_vicente_lachixio,
    oaxaca_san_vicente_nunu, oaxaca_santa_ana, oaxaca_santa_ana_ateixtlahuaca, oaxaca_santa_ana_cuauhtemoc, oaxaca_santa_ana_del_valle,
    oaxaca_santa_ana_tavela, oaxaca_santa_ana_tlapacoyan, oaxaca_santa_ana_yareni, oaxaca_santa_ana_zegache, oaxaca_santa_catalina_quieri,
    oaxaca_santa_catarina_cuixtla, oaxaca_santa_catarina_ixtepeji, oaxaca_santa_catarina_juquila, oaxaca_santa_catarina_lachatao,
    oaxaca_santa_catarina_loxicha, oaxaca_santa_catarina_mechoacan, oaxaca_santa_catarina_minas, oaxaca_santa_catarina_quiane,
    oaxaca_santa_catarina_quioquitani, oaxaca_santa_catarina_tayata, oaxaca_santa_catarina_ticua, oaxaca_santa_catarina_yosonotu,
    oaxaca_santa_catarina_zapoquila, oaxaca_santa_cruz_acatepec, oaxaca_santa_cruz_amilpas, oaxaca_santa_cruz_de_bravo, oaxaca_santa_cruz_itundujia,
    oaxaca_santa_cruz_mixtepec, oaxaca_santa_cruz_nundaco, oaxaca_santa_cruz_papalutla, oaxaca_santa_cruz_tacache_de_mina, oaxaca_santa_cruz_tacahua,
    oaxaca_santa_cruz_tayata, oaxaca_santa_cruz_xitla, oaxaca_santa_cruz_xoxocotlan, oaxaca_santa_cruz_zenzontepec, oaxaca_santa_gertrudis,
    oaxaca_santa_ines_de_zaragoza, oaxaca_santa_ines_del_monte, oaxaca_santa_ines_yatzeche, oaxaca_santa_lucia_del_camino,
    oaxaca_santa_lucia_miahuatlan, oaxaca_santa_lucia_monteverde, oaxaca_santa_lucia_ocotlan, oaxaca_santa_magdalena_jicotlan,
    oaxaca_santa_maria_alotepec, oaxaca_santa_maria_apazco, oaxaca_santa_maria_atzompa, oaxaca_santa_maria_camotlan, oaxaca_santa_maria_chachoapam,
    oaxaca_santa_maria_chilchotla, oaxaca_santa_maria_chimalapa, oaxaca_santa_maria_colotepec, oaxaca_santa_maria_cortijo,
    oaxaca_santa_maria_coyotepec, oaxaca_santa_maria_del_rosario, oaxaca_santa_maria_del_tule, oaxaca_santa_maria_ecatepec,
    oaxaca_santa_maria_guelace, oaxaca_santa_maria_guienagati, oaxaca_santa_maria_huatulco, oaxaca_santa_maria_huazolotitlan,
    oaxaca_santa_maria_ipalapa, oaxaca_santa_maria_ixcatlan, oaxaca_santa_maria_jacatepec, oaxaca_santa_maria_jalapa_del_marques,
    oaxaca_santa_maria_jaltianguis, oaxaca_santa_maria_la_asuncion, oaxaca_santa_maria_lachixio, oaxaca_santa_maria_mixtequilla,
    oaxaca_santa_maria_nativitas, oaxaca_santa_maria_nduayaco, oaxaca_santa_maria_ozolotepec, oaxaca_santa_maria_papalo,
    oaxaca_santa_maria_penoles, oaxaca_santa_maria_petapa, oaxaca_santa_maria_quiegolani, oaxaca_santa_maria_sola, oaxaca_santa_maria_tataltepec,
    oaxaca_santa_maria_tecomavaca, oaxaca_santa_maria_temaxcalapa, oaxaca_santa_maria_temaxcaltepec, oaxaca_santa_maria_teopoxco,
    oaxaca_santa_maria_tepantlali, oaxaca_santa_maria_texcatitlan, oaxaca_santa_maria_tlahuitoltepec, oaxaca_santa_maria_tlalixtac,
    oaxaca_santa_maria_tonameca, oaxaca_santa_maria_totolapilla, oaxaca_santa_maria_xadani, oaxaca_santa_maria_yalina, oaxaca_santa_maria_yavesia,
    oaxaca_santa_maria_yolotepec, oaxaca_santa_maria_yosoyua, oaxaca_santa_maria_yucuhiti, oaxaca_santa_maria_zacatepec, oaxaca_santa_maria_zaniza,
    oaxaca_santa_maria_zoquitlan, oaxaca_santiago_amoltepec, oaxaca_santiago_apoala, oaxaca_santiago_apostol, oaxaca_santiago_astata,
    oaxaca_santiago_atitlan, oaxaca_santiago_ayuquililla, oaxaca_santiago_cacaloxtepec, oaxaca_santiago_camotlan, oaxaca_santiago_chazumba,
    oaxaca_santiago_choapam, oaxaca_santiago_comaltepec, oaxaca_santiago_del_rio, oaxaca_santiago_huajolotitlan, oaxaca_santiago_huauclilla,
    oaxaca_santiago_ihuitlan_plumas, oaxaca_santiago_ixcuintepec, oaxaca_santiago_ixtayutla, oaxaca_santiago_jamiltepec,
    oaxaca_santiago_jocotepec, oaxaca_santiago_juxtlahuaca, oaxaca_santiago_lachiguiri, oaxaca_santiago_lalopa, oaxaca_santiago_laollaga,
    oaxaca_santiago_laxopa, oaxaca_santiago_llano_grande, oaxaca_santiago_matatlan, oaxaca_santiago_miltepec, oaxaca_santiago_minas,
    oaxaca_santiago_nacaltepec, oaxaca_santiago_nejapilla, oaxaca_santiago_niltepec, oaxaca_santiago_nundiche, oaxaca_santiago_nuyoo,
    oaxaca_santiago_pinotepa_nacional, oaxaca_santiago_suchilquitongo, oaxaca_santiago_tamazola, oaxaca_santiago_tapextla, oaxaca_santiago_tenango,
    oaxaca_santiago_tepetlapa, oaxaca_santiago_tetepec, oaxaca_santiago_texcalcingo, oaxaca_santiago_textitlan, oaxaca_santiago_tilantongo,
    oaxaca_santiago_tillo, oaxaca_santiago_tlazoyaltepec, oaxaca_santiago_xanica, oaxaca_santiago_xiacui, oaxaca_santiago_yaitepec,
    oaxaca_santiago_yaveo, oaxaca_santiago_yolomecatl, oaxaca_santiago_yosondua, oaxaca_santiago_yucuyachi, oaxaca_santiago_zacatepec,
    oaxaca_santiago_zoochila, oaxaca_santo_domingo_albarradas, oaxaca_santo_domingo_armenta, oaxaca_santo_domingo_chihuitan,
    oaxaca_santo_domingo_de_morelos, oaxaca_santo_domingo_ingenio, oaxaca_santo_domingo_ixcatlan, oaxaca_santo_domingo_nuxaa,
    oaxaca_santo_domingo_ozolotepec, oaxaca_santo_domingo_petapa, oaxaca_santo_domingo_roayaga, oaxaca_santo_domingo_tehuantepec,
    oaxaca_santo_domingo_teojomulco, oaxaca_santo_domingo_tepuxtepec, oaxaca_santo_domingo_tlatayapam, oaxaca_santo_domingo_tomaltepec,
    oaxaca_santo_domingo_tonala, oaxaca_santo_domingo_tonaltepec, oaxaca_santo_domingo_xagacia, oaxaca_santo_domingo_yanhuitlan,
    oaxaca_santo_domingo_yodohino, oaxaca_santo_domingo_zanatepec, oaxaca_santo_tomas_jalieza, oaxaca_santo_tomas_mazaltepec,
    oaxaca_santo_tomas_ocotepec, oaxaca_santo_tomas_tamazulapan, oaxaca_santos_reyes_nopala, oaxaca_santos_reyes_papalo,
    oaxaca_santos_reyes_tepejillo, oaxaca_santos_reyes_yucuna, oaxaca_silacayoapam, oaxaca_sitio_de_xitlapehua, oaxaca_soledad_etla,
    oaxaca_tamazulapam_del_espiritu_santo, oaxaca_tanetze_de_zaragoza, oaxaca_taniche, oaxaca_tataltepec_de_valdes,
    oaxaca_teococuilco_de_marcos_perez, oaxaca_teotitlan_de_flores_magon, oaxaca_teotitlan_del_valle, oaxaca_teotongo,
    oaxaca_tepelmeme_villa_de_morelos, oaxaca_tezoatlan_de_segura_y_luna, oaxaca_tlacolula_de_matamoros, oaxaca_tlacotepec_plumas,
    oaxaca_tlalixtac_de_cabrera, oaxaca_totontepec_villa_de_morelos, oaxaca_trinidad_zaachila, oaxaca_union_hidalgo, oaxaca_valerio_trujano,
    oaxaca_villa_de_chilapa_de_diaz, oaxaca_villa_de_etla, oaxaca_villa_de_tamazulapam_del_progreso, oaxaca_villa_de_tututepec,
    oaxaca_villa_de_zaachila, oaxaca_villa_diaz_ordaz, oaxaca_villa_hidalgo, oaxaca_villa_sola_de_vega, oaxaca_villa_talea_de_castro,
    oaxaca_villa_tejupam_de_la_union, oaxaca_yaxe, oaxaca_yogana, oaxaca_yutanduchi_de_guerrero, oaxaca_zapotitlan_lagunas,
    oaxaca_zapotitlan_palmas, oaxaca_zimatlan_de_alvarez,
    # PUEBLA
    puebla_acajete, puebla_acateno, puebla_acatlan, puebla_acatzingo, puebla_acteopan, puebla_ahuacatlan, puebla_ahuatlan,
    puebla_ahuazotepec, puebla_ahuehuetitla, puebla_ajalpan, puebla_albino_zertuche, puebla_aljojuca, puebla_altepexi,
    puebla_amixtlan, puebla_amozoc, puebla_aquixtla, puebla_atempan, puebla_atexcal, puebla_atlequizayan, puebla_atlixco,
    puebla_atoyatempan, puebla_atzala, puebla_atzitzihuacan, puebla_atzitzintla, puebla_axutla, puebla_ayotoxco_de_guerrero,
    puebla_calpan, puebla_caltepec, puebla_camocuautla, puebla_canada_morelos, puebla_caxhuacan, puebla_chalchicomula_de_sesma,
    puebla_chapulco, puebla_chiautla, puebla_chiautzingo, puebla_chichiquila, puebla_chiconcuautla, puebla_chietla,
    puebla_chigmecatitlan, puebla_chignahuapan, puebla_chignautla, puebla_chila, puebla_chila_de_la_sal, puebla_chilchotla,
    puebla_chinantla, puebla_coatepec, puebla_coatzingo, puebla_cohetzala, puebla_cohuecan, puebla_coronango, puebla_coxcatlan,
    puebla_coyomeapan, puebla_coyotepec, puebla_cuapiaxtla_de_madero, puebla_cuautempan, puebla_cuautinchan, puebla_cuautlancingo,
    puebla_cuayuca_de_andrade, puebla_cuetzalan_del_progreso, puebla_cuyoaco, puebla_domingo_arenas, puebla_eloxochitlan,
    puebla_epatlan, puebla_esperanza, puebla_francisco_z_mena, puebla_general_felipe_angeles, puebla_guadalupe,
    puebla_guadalupe_victoria, puebla_hermenegildo_galeana, puebla_honey, puebla_huaquechula, puebla_huatlatlauca,
    puebla_huauchinango, puebla_huehuetla, puebla_huehuetlan_el_chico, puebla_huehuetlan_el_grande, puebla_huejotzingo,
    puebla_hueyapan, puebla_hueytamalco, puebla_hueytlalpan, puebla_huitzilan_de_serdan, puebla_huitziltepec,
    puebla_ixcamilpa_de_guerrero, puebla_ixcaquixtla, puebla_ixtacamaxtitlan, puebla_ixtepec, puebla_izucar_de_matamoros,
    puebla_jalpan, puebla_jolalpan, puebla_jonotla, puebla_jopala, puebla_juan_c_bonilla, puebla_juan_galindo, puebla_juan_n_mendez,
    puebla_la_magdalena_tlatlauquitepec, puebla_lafragua, puebla_libres, puebla_los_reyes_de_juarez, puebla_mazapiltepec_de_juarez,
    puebla_mixtla, puebla_molcaxac, puebla_naupan, puebla_nauzontla, puebla_nealtican, puebla_nicolas_bravo, puebla_nopalucan,
    puebla_ocotepec, puebla_ocoyucan, puebla_olintla, puebla_oriental, puebla_pahuatlan, puebla_palmar_de_bravo, puebla_pantepec,
    puebla_petlalcingo, puebla_piaxtla, puebla_puebla, puebla_quecholac, puebla_quimixtlan, puebla_rafael_lara_grajales,
    puebla_san_andres_cholula, puebla_san_antonio_canada, puebla_san_diego_la_mesa_tochimiltzingo, puebla_san_felipe_teotlalcingo,
    puebla_san_felipe_tepatlan, puebla_san_gabriel_chilac, puebla_san_gregorio_atzompa, puebla_san_jeronimo_tecuanipan,
    puebla_san_jeronimo_xayacatlan, puebla_san_jose_chiapa, puebla_san_jose_miahuatlan, puebla_san_juan_atenco,
    puebla_san_juan_atzompa, puebla_san_martin_texmelucan, puebla_san_martin_totoltepec, puebla_san_matias_tlalancaleca,
    puebla_san_miguel_ixitlan, puebla_san_miguel_xoxtla, puebla_san_nicolas_buenos_aires, puebla_san_nicolas_de_los_ranchos,
    puebla_san_pablo_anicano, puebla_san_pedro_cholula, puebla_san_pedro_yeloixtlahuaca, puebla_san_salvador_el_seco,
    puebla_san_salvador_el_verde, puebla_san_salvador_huixcolotla, puebla_san_sebastian_tlacotepec, puebla_santa_catarina_tlaltempan,
    puebla_santa_ines_ahuatempan, puebla_santa_isabel_cholula, puebla_santiago_miahuatlan, puebla_santo_tomas_hueyotlipan, puebla_soltepec,
    puebla_tecali_de_herrera, puebla_tecamachalco, puebla_tecomatlan, puebla_tehuacan, puebla_tehuitzingo, puebla_tenampulco,
    puebla_teopantlan, puebla_teotlalco, puebla_tepanco_de_lopez, puebla_tepango_de_rodriguez, puebla_tepatlaxco_de_hidalgo,
    puebla_tepeaca, puebla_tepemaxalco, puebla_tepeojuma, puebla_tepetzintla, puebla_tepexco, puebla_tepexi_de_rodriguez,
    puebla_tepeyahualco, puebla_tepeyahualco_de_cuauhtemoc, puebla_tetela_de_ocampo, puebla_teteles_de_avila_castillo,
    puebla_teziutlan, puebla_tianguismanalco, puebla_tilapa, puebla_tlachichuca, puebla_tlacotepec_de_benito_juarez,
    puebla_tlacuilotepec, puebla_tlahuapan, puebla_tlaltenango, puebla_tlanepantla, puebla_tlaola, puebla_tlapacoya,
    puebla_tlapanala, puebla_tlatlauquitepec, puebla_tlaxco, puebla_tochimilco, puebla_tochtepec, puebla_totoltepec_de_guerrero,
    puebla_tulcingo, puebla_tuzamapan_de_galeana, puebla_tzicatlacoyan, puebla_venustiano_carranza, puebla_vicente_guerrero,
    puebla_xayacatlan_de_bravo, puebla_xicotepec, puebla_xicotlan, puebla_xiutetelco, puebla_xochiapulco, puebla_xochiltepec,
    puebla_xochitlan_de_vicente_suarez, puebla_xochitlan_todos_santos, puebla_yaonahuac, puebla_yehualtepec, puebla_zacapala,
    puebla_zacapoaxtla, puebla_zacatlan, puebla_zapotitlan, puebla_zapotitlan_de_mendez, puebla_zaragoza, puebla_zautla,
    puebla_zihuateutla, puebla_zinacatepec, puebla_zongozotla, puebla_zoquiapan, puebla_zoquitlan,
    # QUERETARO
    queretaro_amealco_de_bonfil, queretaro_arroyo_seco, queretaro_cadereyta_de_montes, queretaro_colon,
    queretaro_corregidora, queretaro_el_marques, queretaro_ezequiel_montes, queretaro_huimilpan,
    queretaro_jalpan_de_serra, queretaro_landa_de_matamoros, queretaro_pedro_escobedo,
    queretaro_penamiller, queretaro_pinal_de_amoles, queretaro_queretaro, queretaro_san_joaquin,
    queretaro_san_juan_del_rio, queretaro_tequisquiapan, queretaro_toliman,
    # QUINTANA ROO
    quintana_roo_bacalar, quintana_roo_benito_juarez, quintana_roo_cozumel, quintana_roo_felipe_carrillo_puerto,
    quintana_roo_isla_mujeres, quintana_roo_jose_maria_morelos, quintana_roo_lazaro_cardenas, quintana_roo_othon_p_blanco,
    quintana_roo_puerto_morelos, quintana_roo_solidaridad, quintana_roo_tulum,
    # SAN LUIS POTOSI
    san_luis_potosi_ahualulco, san_luis_potosi_alaquines, san_luis_potosi_aquismon, san_luis_potosi_armadillo_de_los_infante,
    san_luis_potosi_axtla_de_terrazas, san_luis_potosi_cardenas, san_luis_potosi_catorce, san_luis_potosi_cedral,
    san_luis_potosi_cerritos, san_luis_potosi_cerro_de_san_pedro, san_luis_potosi_charcas, san_luis_potosi_ciudad_del_maiz,
    san_luis_potosi_ciudad_fernandez, san_luis_potosi_ciudad_valles, san_luis_potosi_coxcatlan, san_luis_potosi_ebano,
    san_luis_potosi_el_naranjo, san_luis_potosi_guadalcazar, san_luis_potosi_huehuetlan, san_luis_potosi_lagunillas,
    san_luis_potosi_matehuala, san_luis_potosi_matlapa, san_luis_potosi_mexquitic_de_carmona, san_luis_potosi_moctezuma,
    san_luis_potosi_rayon, san_luis_potosi_rioverde, san_luis_potosi_salinas, san_luis_potosi_san_antonio,
    san_luis_potosi_san_ciro_de_acosta, san_luis_potosi_san_luis_potosi, san_luis_potosi_san_martin_chalchicuautla,
    san_luis_potosi_san_nicolas_tolentino, san_luis_potosi_san_vicente_tancuayalab, san_luis_potosi_santa_catarina,
    san_luis_potosi_santa_maria_del_rio, san_luis_potosi_santo_domingo, san_luis_potosi_soledad_de_graciano_sanchez,
    san_luis_potosi_tamasopo, san_luis_potosi_tamazunchale, san_luis_potosi_tampacan, san_luis_potosi_tampamolon_corona,
    san_luis_potosi_tamuin, san_luis_potosi_tancanhuitz, san_luis_potosi_tanlajas, san_luis_potosi_tanquian_de_escobedo,
    san_luis_potosi_tierra_nueva, san_luis_potosi_vanegas, san_luis_potosi_venado, san_luis_potosi_villa_de_arista,
    san_luis_potosi_villa_de_arriaga, san_luis_potosi_villa_de_guadalupe, san_luis_potosi_villa_de_la_paz,
    san_luis_potosi_villa_de_ramos, san_luis_potosi_villa_de_reyes, san_luis_potosi_villa_hidalgo,
    san_luis_potosi_villa_juarez, san_luis_potosi_xilitla, san_luis_potosi_zaragoza,
    # SINALOA
    sinaloa_ahome, sinaloa_angostura, sinaloa_badiraguato, sinaloa_choix, sinaloa_concordia,
    sinaloa_cosala, sinaloa_culiacan, sinaloa_el_fuerte, sinaloa_elota, sinaloa_escuinapa,
    sinaloa_guasave, sinaloa_mazatlan, sinaloa_mocorito, sinaloa_navolato, sinaloa_rosario,
    sinaloa_salvador_alvarado, sinaloa_san_ignacio, sinaloa_sinaloa,
    # SONORA
    sonora_aconchi, sonora_agua_prieta, sonora_alamos, sonora_altar, sonora_arivechi, sonora_arizpe,
    sonora_atil, sonora_bacadehuachi, sonora_bacanora, sonora_bacerac, sonora_bacoachi, sonora_bacum,
    sonora_banamichi, sonora_baviacora, sonora_bavispe, sonora_benito_juarez, sonora_benjamin_hill,
    sonora_caborca, sonora_cajeme, sonora_cananea, sonora_carbo, sonora_cucurpe, sonora_cumpas,
    sonora_divisaderos, sonora_empalme, sonora_etchojoa, sonora_fronteras, sonora_general_plutarco_elias_calles,
    sonora_granados, sonora_guaymas, sonora_hermosillo, sonora_huachinera, sonora_huasabas, sonora_huatabampo,
    sonora_huepac, sonora_imuris, sonora_la_colorada, sonora_magdalena, sonora_mazatan, sonora_moctezuma,
    sonora_naco, sonora_nacori_chico, sonora_nacozari_de_garcia, sonora_navojoa, sonora_nogales, sonora_onavas,
    sonora_opodepe, sonora_oquitoa, sonora_pitiquito, sonora_puerto_penasco, sonora_quiriego, sonora_rayon,
    sonora_rosario, sonora_sahuaripa, sonora_san_felipe_de_jesus, sonora_san_ignacio_rio_muerto,
    sonora_san_javier, sonora_san_luis_rio_colorado, sonora_san_miguel_de_horcasitas,
    sonora_san_pedro_de_la_cueva, sonora_santa_ana, sonora_santa_cruz, sonora_saric, sonora_soyopa,
    sonora_suaqui_grande, sonora_tepache, sonora_trincheras, sonora_tubutama, sonora_ures, sonora_villa_hidalgo,
    sonora_villa_pesqueira, sonora_yecora,
    # TABASCO
    tabasco_balancan, tabasco_cardenas, tabasco_centla, tabasco_centro, tabasco_comalcalco,
    tabasco_cunduacan, tabasco_emiliano_zapata, tabasco_huimanguillo, tabasco_jalapa,
    tabasco_jalpa_de_mendez, tabasco_jonuta, tabasco_macuspana, tabasco_nacajuca, tabasco_paraiso,
    tabasco_tacotalpa, tabasco_teapa, tabasco_tenosique,
    # TAMAULIPAS
    tamaulipas_abasolo, tamaulipas_aldama, tamaulipas_altamira, tamaulipas_antiguo_morelos, tamaulipas_burgos,
    tamaulipas_bustamante, tamaulipas_camargo, tamaulipas_casas, tamaulipas_ciudad_madero, tamaulipas_cruillas,
    tamaulipas_el_mante, tamaulipas_gomez_farias, tamaulipas_gonzalez, tamaulipas_guemez, tamaulipas_guerrero,
    tamaulipas_gustavo_diaz_ordaz, tamaulipas_hidalgo, tamaulipas_jaumave, tamaulipas_jimenez, tamaulipas_llera,
    tamaulipas_mainero, tamaulipas_matamoros, tamaulipas_mendez, tamaulipas_mier, tamaulipas_miguel_aleman,
    tamaulipas_miquihuana, tamaulipas_nuevo_laredo, tamaulipas_nuevo_morelos, tamaulipas_ocampo, tamaulipas_padilla,
    tamaulipas_palmillas, tamaulipas_reynosa, tamaulipas_rio_bravo, tamaulipas_san_carlos, tamaulipas_san_fernando,
    tamaulipas_san_nicolas, tamaulipas_soto_la_marina, tamaulipas_tampico, tamaulipas_tula, tamaulipas_valle_hermoso,
    tamaulipas_victoria, tamaulipas_villagran, tamaulipas_xicotencatl,
    # TLAXCALA
    tlaxcala_acuamanala_de_miguel_hidalgo, tlaxcala_amaxac_de_guerrero, tlaxcala_apetatitlan_de_antonio_carvajal,
    tlaxcala_apizaco, tlaxcala_atlangatepec, tlaxcala_atltzayanca, tlaxcala_benito_juarez, tlaxcala_calpulalpan,
    tlaxcala_chiautempan, tlaxcala_contla_de_juan_cuamatzi, tlaxcala_cuapiaxtla, tlaxcala_cuaxomulco,
    tlaxcala_el_carmen_tequexquitla, tlaxcala_emiliano_zapata, tlaxcala_espanita, tlaxcala_huamantla,
    tlaxcala_hueyotlipan, tlaxcala_ixtacuixtla_de_mariano_matamoros, tlaxcala_ixtenco, tlaxcala_la_magdalena_tlaltelulco,
    tlaxcala_lazaro_cardenas, tlaxcala_mazatecochco_de_jose_maria_morelos, tlaxcala_munoz_de_domingo_arenas,
    tlaxcala_nanacamilpa_de_mariano_arista, tlaxcala_nativitas, tlaxcala_panotla, tlaxcala_papalotla_de_xicohtencatl,
    tlaxcala_san_damian_texoloc, tlaxcala_san_francisco_tetlanohcan, tlaxcala_san_jeronimo_zacualpan,
    tlaxcala_san_jose_teacalco, tlaxcala_san_juan_huactzinco, tlaxcala_san_lorenzo_axocomanitla, tlaxcala_san_lucas_tecopilco,
    tlaxcala_san_pablo_del_monte, tlaxcala_sanctorum_de_lazaro_cardenas, tlaxcala_santa_ana_nopalucan,
    tlaxcala_santa_apolonia_teacalco, tlaxcala_santa_catarina_ayometla, tlaxcala_santa_cruz_quilehtla,
    tlaxcala_santa_cruz_tlaxcala, tlaxcala_santa_isabel_xiloxoxtla, tlaxcala_tenancingo, tlaxcala_teolocholco,
    tlaxcala_tepetitla_de_lardizabal, tlaxcala_tepeyanco, tlaxcala_terrenate, tlaxcala_tetla_de_la_solidaridad,
    tlaxcala_tetlatlahuca, tlaxcala_tlaxcala, tlaxcala_tlaxco, tlaxcala_tocatlan, tlaxcala_totolac, tlaxcala_tzompantepec,
    tlaxcala_xaloztoc, tlaxcala_xaltocan, tlaxcala_xicohtzinco, tlaxcala_yauhquemehcan, tlaxcala_zacatelco,
    tlaxcala_ziltlaltepec_de_trinidad_sanchez_santos,
    # VERACRUZ
    veracruz_acajete, veracruz_acatlan, veracruz_acayucan, veracruz_actopan, veracruz_acula, veracruz_acultzingo,
    veracruz_agua_dulce, veracruz_alamo_temapache, veracruz_alpatlahuac, veracruz_alto_lucero_de_gutierrez_barrios,
    veracruz_altotonga, veracruz_alvarado, veracruz_amatitlan, veracruz_amatlan_de_los_reyes, veracruz_angel_r_cabada,
    veracruz_apazapan, veracruz_aquila, veracruz_astacinga, veracruz_atlahuilco, veracruz_atoyac, veracruz_atzacan,
    veracruz_atzalan, veracruz_ayahualulco, veracruz_banderilla, veracruz_benito_juarez, veracruz_boca_del_rio,
    veracruz_calcahualco, veracruz_camaron_de_tejeda, veracruz_camerino_z_mendoza, veracruz_carlos_a_carrillo,
    veracruz_carrillo_puerto, veracruz_castillo_de_teayo, veracruz_catemaco, veracruz_cazones_de_herrera,
    veracruz_cerro_azul, veracruz_chacaltianguis, veracruz_chalma, veracruz_chiconamel, veracruz_chiconquiaco,
    veracruz_chicontepec, veracruz_chinameca, veracruz_chinampa_de_gorostiza, veracruz_chocaman, veracruz_chontla,
    veracruz_chumatlan, veracruz_citlaltepetl, veracruz_coacoatzintla, veracruz_coahuitlan, veracruz_coatepec,
    veracruz_coatzacoalcos, veracruz_coatzintla, veracruz_coetzala, veracruz_colipa, veracruz_comapa, veracruz_cordoba,
    veracruz_cosamaloapan_de_carpio, veracruz_cosautlan_de_carvajal, veracruz_coscomatepec, veracruz_cosoleacaque,
    veracruz_cotaxtla, veracruz_coxquihui, veracruz_coyutla, veracruz_cuichapa, veracruz_cuitlahuac, veracruz_el_higo,
    veracruz_emiliano_zapata, veracruz_espinal, veracruz_filomeno_mata, veracruz_fortin, veracruz_gutierrez_zamora,
    veracruz_hidalgotitlan, veracruz_huatusco, veracruz_huayacocotla, veracruz_hueyapan_de_ocampo,
    veracruz_huiloapan_de_cuauhtemoc, veracruz_ignacio_de_la_llave, veracruz_ilamatlan, veracruz_isla, veracruz_ixcatepec,
    veracruz_ixhuacan_de_los_reyes, veracruz_ixhuatlan_de_madero, veracruz_ixhuatlan_del_cafe, veracruz_ixhuatlan_del_sureste,
    veracruz_ixhuatlancillo, veracruz_ixmatlahuacan, veracruz_ixtaczoquitlan, veracruz_jalacingo, veracruz_jalcomulco,
    veracruz_jaltipan, veracruz_jamapa, veracruz_jesus_carranza, veracruz_jilotepec, veracruz_jose_azueta,
    veracruz_juan_rodriguez_clara, veracruz_juchique_de_ferrer, veracruz_la_antigua, veracruz_la_perla, veracruz_landero_y_coss,
    veracruz_las_choapas, veracruz_las_minas, veracruz_las_vigas_de_ramirez, veracruz_lerdo_de_tejada, veracruz_los_reyes,
    veracruz_magdalena, veracruz_maltrata, veracruz_manlio_fabio_altamirano, veracruz_mariano_escobedo, veracruz_martinez_de_la_torre,
    veracruz_mecatlan, veracruz_mecayapan, veracruz_medellin_de_bravo, veracruz_miahuatlan, veracruz_minatitlan, veracruz_misantla,
    veracruz_mixtla_de_altamirano, veracruz_moloacan, veracruz_nanchital_de_lazaro_cardenas_del_rio, veracruz_naolinco,
    veracruz_naranjal, veracruz_naranjos_amatlan, veracruz_nautla, veracruz_nogales, veracruz_oluta, veracruz_omealca,
    veracruz_orizaba, veracruz_otatitlan, veracruz_oteapan, veracruz_ozuluama_de_mascarenas, veracruz_pajapan, veracruz_panuco,
    veracruz_papantla, veracruz_paso_de_ovejas, veracruz_paso_del_macho, veracruz_perote, veracruz_platon_sanchez, veracruz_playa_vicente,
    veracruz_poza_rica_de_hidalgo, veracruz_pueblo_viejo, veracruz_puente_nacional, veracruz_rafael_delgado, veracruz_rafael_lucio,
    veracruz_rio_blanco, veracruz_saltabarranca, veracruz_san_andres_tenejapan, veracruz_san_andres_tuxtla, veracruz_san_juan_evangelista,
    veracruz_san_rafael, veracruz_santiago_sochiapan, veracruz_santiago_tuxtla, veracruz_sayula_de_aleman, veracruz_sochiapa,
    veracruz_soconusco, veracruz_soledad_atzompa, veracruz_soledad_de_doblado, veracruz_soteapan, veracruz_tamalin, veracruz_tamiahua,
    veracruz_tampico_alto, veracruz_tancoco, veracruz_tantima, veracruz_tantoyuca, veracruz_tatahuicapan_de_juarez, veracruz_tatatila,
    veracruz_tecolutla, veracruz_tehuipango, veracruz_tempoal, veracruz_tenampa, veracruz_tenochtitlan, veracruz_teocelo, veracruz_tepatlaxco,
    veracruz_tepetlan, veracruz_tepetzintla, veracruz_tequila, veracruz_texcatepec, veracruz_texhuacan, veracruz_texistepec, veracruz_tezonapa,
    veracruz_tierra_blanca, veracruz_tihuatlan, veracruz_tlachichilco, veracruz_tlacojalpan, veracruz_tlacolulan, veracruz_tlacotalpan,
    veracruz_tlacotepec_de_mejia, veracruz_tlalixcoyan, veracruz_tlalnelhuayocan, veracruz_tlaltetela, veracruz_tlapacoyan, veracruz_tlaquilpa,
    veracruz_tlilapan, veracruz_tomatlan, veracruz_tonayan, veracruz_totutla, veracruz_tres_valles, veracruz_tuxpan, veracruz_tuxtilla,
    veracruz_ursulo_galvan, veracruz_uxpanapa, veracruz_vega_de_alatorre, veracruz_veracruz, veracruz_villa_aldama, veracruz_xalapa,
    veracruz_xico, veracruz_xoxocotla, veracruz_yanga, veracruz_yecuatla, veracruz_zacualpan, veracruz_zaragoza, veracruz_zentla,
    veracruz_zongolica, veracruz_zontecomatlan_de_lopez_y_fuentes, veracruz_zozocolco_de_hidalgo,
    # YUCATAN
    yucatan_abala, yucatan_acanceh, yucatan_akil, yucatan_baca, yucatan_bokoba, yucatan_buctzotz,
    yucatan_cacalchen, yucatan_calotmul, yucatan_cansahcab, yucatan_cantamayec, yucatan_celestun,
    yucatan_cenotillo, yucatan_chacsinkin, yucatan_chankom, yucatan_chapab, yucatan_chemax, yucatan_chichimila,
    yucatan_chicxulub_pueblo, yucatan_chikindzonot, yucatan_chochola, yucatan_chumayel, yucatan_conkal, yucatan_cuncunul,
    yucatan_cuzama, yucatan_dzan, yucatan_dzemul, yucatan_dzidzantun, yucatan_dzilam_de_bravo, yucatan_dzilam_gonzalez,
    yucatan_dzitas, yucatan_dzoncauich, yucatan_espita, yucatan_halacho, yucatan_hocaba, yucatan_hoctun, yucatan_homun,
    yucatan_huhi, yucatan_hunucma, yucatan_ixil, yucatan_izamal, yucatan_kanasin, yucatan_kantunil, yucatan_kaua,
    yucatan_kinchil, yucatan_kopoma, yucatan_mama, yucatan_mani, yucatan_maxcanu, yucatan_mayapan, yucatan_merida,
    yucatan_mococha, yucatan_motul, yucatan_muna, yucatan_muxupip, yucatan_opichen, yucatan_oxkutzcab, yucatan_panaba,
    yucatan_peto, yucatan_progreso, yucatan_quintana_roo, yucatan_rio_lagartos, yucatan_sacalum, yucatan_samahil,
    yucatan_san_felipe, yucatan_sanahcat, yucatan_santa_elena, yucatan_seye, yucatan_sinanche, yucatan_sotuta,
    yucatan_sucila, yucatan_sudzal, yucatan_suma, yucatan_tahdziu, yucatan_tahmek, yucatan_teabo, yucatan_tecoh,
    yucatan_tekal_de_venegas, yucatan_tekanto, yucatan_tekax, yucatan_tekit, yucatan_tekom, yucatan_telchac_pueblo,
    yucatan_telchac_puerto, yucatan_temax, yucatan_temozon, yucatan_tepakan, yucatan_tetiz, yucatan_teya, yucatan_ticul,
    yucatan_timucuy, yucatan_tinum, yucatan_tixcacalcupul, yucatan_tixkokob, yucatan_tixmehuac, yucatan_tixpehual,
    yucatan_tizimin, yucatan_tunkas, yucatan_tzucacab, yucatan_uayma, yucatan_ucu, yucatan_uman, yucatan_valladolid,
    yucatan_xocchel, yucatan_yaxcaba, yucatan_yaxkukul, yucatan_yobain,
    # ZACATECAS
    zacatecas_apozol, zacatecas_apulco, zacatecas_atolinga, zacatecas_benito_juarez, zacatecas_calera,
    zacatecas_canitas_de_felipe_pescador, zacatecas_chalchihuites, zacatecas_concepcion_del_oro,
    zacatecas_cuauhtemoc, zacatecas_el_plateado_de_joaquin_amaro, zacatecas_el_salvador, zacatecas_fresnillo,
    zacatecas_genaro_codina, zacatecas_general_enrique_estrada, zacatecas_general_francisco_r_murguia,
    zacatecas_general_panfilo_natera, zacatecas_guadalupe, zacatecas_huanusco, zacatecas_jalpa, zacatecas_jerez,
    zacatecas_jimenez_del_teul, zacatecas_juan_aldama, zacatecas_juchipila, zacatecas_loreto, zacatecas_luis_moya,
    zacatecas_mazapil, zacatecas_melchor_ocampo, zacatecas_mezquital_del_oro, zacatecas_miguel_auza, zacatecas_momax,
    zacatecas_monte_escobedo, zacatecas_morelos, zacatecas_moyahua_de_estrada, zacatecas_nochistlan_de_mejia,
    zacatecas_noria_de_angeles, zacatecas_ojocaliente, zacatecas_panuco, zacatecas_pinos, zacatecas_rio_grande,
    zacatecas_sain_alto, zacatecas_santa_maria_de_la_paz, zacatecas_sombrerete, zacatecas_susticacan, zacatecas_tabasco,
    zacatecas_tepechitlan, zacatecas_tepetongo, zacatecas_teul_de_gonzalez_ortega, zacatecas_tlaltenango_de_sanchez_roman,
    zacatecas_trancoso, zacatecas_trinidad_garcia_de_la_cadena, zacatecas_valparaiso, zacatecas_vetagrande,
    zacatecas_villa_de_cos, zacatecas_villa_garcia, zacatecas_villa_gonzalez_ortega, zacatecas_villa_hidalgo,
    zacatecas_villanueva, zacatecas_zacatecas
])
new_result = result.applymap(str)

# REPLACING ACCENTS
new_result.replace(to_replace=r'á', value='a', regex=True,inplace=True)
new_result.replace(to_replace=r'é', value='e', regex=True,inplace=True)
new_result.replace(to_replace=r'í', value='i', regex=True,inplace=True)
new_result.replace(to_replace=r'ó', value='o', regex=True,inplace=True)
new_result.replace(to_replace=r'ú', value='u', regex=True,inplace=True)
new_result.replace(to_replace=r'ä', value='a', regex=True,inplace=True)
new_result.replace(to_replace=r'ë', value='e', regex=True,inplace=True)
new_result.replace(to_replace=r'ï', value='i', regex=True,inplace=True)
new_result.replace(to_replace=r'ö', value='o', regex=True,inplace=True)
new_result.replace(to_replace=r'ü', value='u', regex=True,inplace=True)
new_result.replace(to_replace=r'Á', value='A', regex=True,inplace=True)
new_result.replace(to_replace=r'É', value='E', regex=True,inplace=True)
new_result.replace(to_replace=r'Í', value='I', regex=True,inplace=True)
new_result.replace(to_replace=r'Ó', value='O', regex=True,inplace=True)
new_result.replace(to_replace=r'Ú', value='U', regex=True,inplace=True)

# DROP DUPLICATES DATA MICODIGOPOSTAL CASE LIKE THIS: 
"""
San Juan	Colonia     29140	Ocozocoautla de Espinosa    Ocozocoautla de Espinosa    Urbana      Mapa
San Juan	Barrio      29140	Ocozocoautla de Espinosa    Ocozocoautla de Espinosa    Urbana      Mapa
"""
new_results = new_result.drop_duplicates()